services:
  analytics-service:
    image: analytics-service-image:latest
    container_name: analytics-service-container
    build: .
    ports:
      - "4002:4002"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

    networks:
      - patients-management-network


networks:
  patients-management-network:
    external: true





